export const tagTypes = {
  auth: "auth",
  user: "user",
  home_about_section: "home-about-section",
  home_hero_section: "home-hero-section",
  education: "education",
  experience: "experience",
  projects: "projects",
  project_categories: "project-categories",
  faqs: "faqs",
  faq_answers: "faq-ans",
  testimonials: "testimonials",
  skills: "skills",
  skills_category: "skills-category",
  collaborating: "collaborating",
  extra_curriculum_categories: "extra-curriculum-categories",
  extra_curriculum: "extra-curriculum",
  article_categories: "article-categories",
  articles: "articles",
  project_details: "project-details",
  collaborate: "collaborate",
  about_me: "about-me",
  my_hobbies: "my-hobbies",
  snapshots_category: "snapshots-category",
  snapshots: "snapshots",
  section_description: "section-description",
  research_and_publications: "research-and-publications",
  article_details: "article-details",
  send_messages: "send-messages",
  professors: "professors",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.home_about_section,
  tagTypes.home_hero_section,
  tagTypes.education,
  tagTypes.experience,
  tagTypes.projects,
  tagTypes.project_categories,
  tagTypes.faqs,
  tagTypes.faq_answers,
  tagTypes.testimonials,
  tagTypes.skills,
  tagTypes.skills_category,
  tagTypes.collaborating,
  tagTypes.extra_curriculum_categories,
  tagTypes.extra_curriculum,
  tagTypes.article_categories,
  tagTypes.articles,
  tagTypes.project_details,
  tagTypes.collaborate,
  tagTypes.about_me,
  tagTypes.my_hobbies,
  tagTypes.snapshots_category,
  tagTypes.snapshots,
  tagTypes.section_description,
  tagTypes.research_and_publications,
  tagTypes.article_details,
  tagTypes.send_messages,
  tagTypes.professors,
];
