export const tagTypes = {
  auth: "auth",
  user: "user",
  home_about_section: "home-about-section",
  heroes: "heroes",
  our_work_process: "our-work-process",
  categories: "categories",
  services: "services",
  service_faqs: "service-faqs",
  service_reviews: "service-reviews",
  projects: "projects",
  project_categories: "project-categories",
  faqs: "faqs",
  faq_answers: "faq-ans",
  testimonials: "testimonials",
  skills: "skills",
  skills_category: "skills-category",
  collaborating: "collaborating",
  extra_curriculum_categories: "extra-curriculum-categories",
  extra_curriculum: "extra-curriculum",
  article_categories: "article-categories",
  articles: "articles",
};

export const tagTypesList = [
  tagTypes.auth,
  tagTypes.user,
  tagTypes.home_about_section,
  tagTypes.heroes,
  tagTypes.our_work_process,
  tagTypes.categories,
  tagTypes.services,
  tagTypes.service_faqs,
  tagTypes.service_reviews,
  tagTypes.projects,
  tagTypes.project_categories,
  tagTypes.faqs,
  tagTypes.faq_answers,
  tagTypes.testimonials,
  tagTypes.skills,
  tagTypes.skills_category,
  tagTypes.collaborating,
  tagTypes.extra_curriculum_categories,
  tagTypes.extra_curriculum,
  tagTypes.article_categories,
  tagTypes.articles,
  tagTypes.project_details,
];
